version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx-imis
    tty: true
    ports:
      - 80:80
    # SSL
    # - 443:443
    volumes:
      - ./src/base-imis:/var/www/html/imis:delegated
    #SSL
    #  - ./ssl:/etc/ssl/private:ro

    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php-imis
    volumes:
      - ./src/base-imis:/var/www/html/imis:delegated
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer-imis
    volumes:
      - ./src/base-imis:/var/www/html/imis
    working_dir: /var/www/html/imis
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm-imis
    volumes:
      - ./src/base-imis:/var/www/html/imis
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html/imis
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan-imis
    volumes:
      - ./src/base-imis:/var/www/html/imis:delegated
    working_dir: /var/www/html/imis
    entrypoint: ['php', '/var/www/html/imis/artisan']
    networks:
      - laravel
